version: '3.5'
services:

  composer:
    image: prooph/composer:7.2
    volumes:
      - ".:/app"
    working_dir: /app
    environment:
      MONGO_HOST: mongo
      SYMFONY_PHPUNIT_VERSION: 7.4

  mongo:
    image: mongo:4.0
    command: --smallfiles

  dockerize:
    image: jwilder/dockerize
